name: idp-tutorials-test
channels:
- conda-forge
dependencies:
- pip
- bokeh=3.8.0
- cartopy=0.25.0
- colorcet=3.1.0
- dask
- dask-geopandas=0.5.0
- fsspec=2025.9.0
- geopandas=1.1.1
- geoviews=1.14.1
- holoviews=1.21.0
- hvplot=0.12.1
- ipykernel=6.30.1
- ipyleaflet=0.20.0
- jupyterlab-myst=2.4.2
- matplotlib=3.10.6
- nbformat=5.10.4
- pandas=2.3.3
- pathlib=1.0.1
- pip=25.2
- plotly=6.3.1
- pyam=1.6.0
- pystac=1.14.1
- pystac-client=0.9.0
- python=3.13.7
- python-dotenv=1.1.1
- python-kaleido=1.2.0
- rasterio=1.4.3
- requests=2.32.5
- rioxarray=0.19.0
- shapely=2.1.2
- spatialpandas=0.5.0
- stac-geoparquet=0.7.0
- typing=3.10.0.0
- xarray=2025.10.1
- zarr=3.1.3
- pip:
    - adlfs==2025.8.0
    - gcsfs==2025.9.0
    - aiohttp==3.13.2

